# Generated by Django 5.0.2 on 2024-02-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('EQ', 'Earthquake'), ('WF', 'Wildfires'), ('VC', 'Volcanoes'), ('TD', 'Tornado'), ('SM', 'Storm'), ('HC', 'Hurricanes'), ('AV', 'Avalanche'), ('DT', 'Drought'), ('BD', 'Blizzard'), ('WD', 'Windstorm'), ('TS', 'Tsunami'), ('LS', 'Landslide'), ('DF', 'Deforestation'), ('FD', 'Flood')], max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
