# Generated by Django 5.0.2 on 2024-02-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_charity_options_alter_media_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
