# Generated by Django 5.0.2 on 2024-02-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_disaster_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='type',
            field=models.CharField(choices=[('EQ', 'Earthquake'), ('WF', 'Wildfires'), ('VC', 'Volcano'), ('TD', 'Tornado'), ('SM', 'Storm'), ('HC', 'Hurricane'), ('AV', 'Avalanche'), ('DT', 'Drought'), ('BD', 'Blizzard'), ('WD', 'Windstorm'), ('TS', 'Tsunami'), ('LS', 'Landslide'), ('DF', 'Deforestation'), ('FD', 'Flood')], max_length=2),
        ),
    ]
