# Generated by Django 5.0.2 on 2024-02-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_disaster_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='type',
            field=models.CharField(choices=[('EQ', 'Earthquake'), ('WF', 'Wildfires'), ('VC', 'Volcano'), ('SM', 'Storm'), ('HC', 'Hurricane'), ('DF', 'Deforestation'), ('FD', 'Flood')], max_length=2),
        ),
    ]
