# Generated by Django 5.0.2 on 2024-02-10 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_disaster_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='disaster',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.disastertype'),
        ),
    ]
