# Generated by Django 5.0.2 on 2024-02-10 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_disaster_disaster_type_alter_disaster_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaster',
            name='type',
        ),
    ]
