# Generated by Django 5.0.2 on 2024-02-10 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_remove_disaster_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disastertype',
            options={'verbose_name_plural': 'Disaster Types'},
        ),
    ]
