# Generated by Django 5.0.2 on 2024-02-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_alter_disastertype_options_disastertype_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disastertype',
            old_name='image',
            new_name='icon',
        ),
    ]
