# Generated by Django 5.0.2 on 2024-02-10 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_alter_disastertype_options'),
        ('map', '0011_rename_image_disastertype_icon'),
    ]

    operations = [
    ]
